services:
  mai_os:
    build: .
    stdin_open: true
    tty: true
    command: sleep infinity
    develop:
      watch:
         - action: sync
           path: .
           target: /workspace
